run:
  modules-download-mode: vendor

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - exportloopref
    - exportloopref
    - forbidigo
    - godox
    - goerr113
    - gofmt
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - makezero
    - misspell
    - musttag
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - stylecheck
    - tparallel
    - unconvert
    - usestdlibvars
    - wastedassign
    - whitespace
